image: wodby/php:8.3

pipelines:
    default:
        - step:
            caches:
              - composer
            name: Composer validate
            script:
                - composer install
                - composer validate --no-check-version --no-check-publish
        - step:
            caches:
              - composer
            name: Composer install
            script:
                - composer install
