image: wodby/php:8.3

pipelines:
    default:
        - step:
            caches:
              - composer
            name: Composer validate
            script:
                - composer install
                - composer ci:validate
        - step:
            caches:
              - composer
            name: Composer install
            script:
                - composer install
