name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  composer-validate:
    name: Composer validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Composer validate
        run: composer validate --no-check-version --no-check-publish

  composer-install:
    name: Composer install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer --verbose install

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    container:
      image: wodby/drupal-php:8.3
      options: --user 1001
    services:
      php:
        image: wodby/drupal-php:8.3
        volumes:
          - ${{ github.workspace }}:/var/www/html
      web:
        image: wodby/nginx:1
        volumes:
          - ${{ github.workspace }}:/var/www/html
      db:
        image: mysql:8.0
      chromedriver:
        image: selenium/standalone-chromium:137.0-chromedriver-137.0
        ports:
          - 4444:4444
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
      - name: Show user info (debug)
        run: id && whoami
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: composer --verbose install

      - run: ls -lah /

      - name: Install Drupal
        run: composer site-install

      - name: Run PHPUnit
        run: composer phpunit
        env:
          DTT_BASE_URL: "http://web"
          DTT_MINK_DRIVER_ARGS: "[\"chrome\", {\"browserName\":\"chrome\",\"goog:chromeOptions\":{\"w3c\":false,\"args\":[\"--headless\", \"--disable-gpu\", \"--no-sandbox\", \"--disable-dev-shm-usage\"]}}, \"http://chromedriver:4444/wd/hub\"]"
