name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  composer-validate:
    name: Composer validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Composer validate
        run: composer validate --no-check-version --no-check-publish

  composer-install:
    name: Composer install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer --verbose install

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    services:
      chromedriver:
        image: selenium/standalone-chromium
        ports:
          - 4444:4444
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer --verbose install

      - name: Install Drupal
        run: composer site-install

      - run: curl localhost:4444/wd/hub/status

      - name: Run PHPUnit
        run: composer phpunit
